-- FILE: db_schema.sql
-- (This file is for reference/backup only. The app does not read this file.)

-- ==========================================
-- 1. SETUP TABLES
-- ==========================================

-- 1. Profiles Table (Managed by Supabase Auth)
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text
);

-- 2. Tasks Table (For the Syllabus Sync)
create table tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  course_code text, -- e.g., COP2510
  assignment_name text,
  due_date date,
  is_completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Chat Messages (For the Roast Room)
create table messages (
  id bigint generated by default as identity primary key,
  course_room text not null, -- e.g., 'USF_General'
  user_id uuid references auth.users not null,
  content text,
  is_roast boolean default false, -- TRUE if the AI posted it
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ==========================================
-- 2. SECURITY & PERMISSIONS
-- ==========================================

-- Enable Realtime for Chat
alter publication supabase_realtime add table messages;

-- TEMPORARY HACK: Disable Security so you don't get permission errors
alter table profiles enable row level security;
alter table tasks enable row level security;
alter table messages enable row level security;

create policy "Enable all access for everyone" on profiles for all using (true) with check (true);
create policy "Enable all access for everyone" on tasks for all using (true) with check (true);
create policy "Enable all access for everyone" on messages for all using (true) with check (true);

-- ==========================================
-- 3. FAKE DATA (SEED)
-- ==========================================

-- Room: COP2510 (Programming Concepts)
INSERT INTO messages (course_room, user_id, content, is_roast, created_at) VALUES

-- 1. Student 1 asks a question (20 mins ago)
('COP2510', 'fe4360e2-c277-48e7-a80c-9d1a13462d04', 'wait is pointers on the midterm tmrw?', false, now() - interval '20 minutes'),

-- 2. Student 2 replies (18 mins ago)
('COP2510', 'bd32df9e-cfef-4dfc-850e-516223046378', 'yea prof said everything up to linked lists', false, now() - interval '18 minutes'),

-- 3. Student 1 reacts (15 mins ago)
('COP2510', 'fe4360e2-c277-48e7-a80c-9d1a13462d04', 'damn ok. im at the lib 5th floor if anyone wants to study', false, now() - interval '15 minutes'),

-- 4. YOU join in (10 mins ago)
('COP2510', 'ad01040d-d455-4368-9dcf-6e655c05b542', 'omw. gonna try to lock in for 2 hours.', false, now() - interval '10 minutes'),

-- 5. THE ROAST (The System catches YOU 9 mins ago)
('COP2510', 'ad01040d-d455-4368-9dcf-6e655c05b542', '🚨 ALERT: Focus Mode Failed. Object Detected: IPHONE. Activity: Instagram. Shame!', true, now() - interval '9 minutes'),

-- 6. Student 2 laughs (8 mins ago)
('COP2510', 'bd32df9e-cfef-4dfc-850e-516223046378', 'lol already?', false, now() - interval '8 minutes'),

-- 7. System Penalty (5 mins ago)
('COP2510', 'ad01040d-d455-4368-9dcf-6e655c05b542', 'SYSTEM: -50 XP. Streak reset.', true, now() - interval '5 minutes'),

-- 8. You reply (2 mins ago)
('COP2510', 'ad01040d-d455-4368-9dcf-6e655c05b542', 'my bad lol. phone is off now.', false, now() - interval '2 minutes');